repos:
  - repo: https://github.com/hadialqattan/pycln
    rev: v1.1.0
    hooks:
      - id: pycln
        args: [--config=pycln.toml]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-ast
      - id: debug-statements
  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black # to disable black in a section code, use: # fmt: off, and then: # fmt: on
        language_version: python3.8
        exclude: migrations|manage.py
        args: [--line-length=120, --exclude=/(\.git|\.venv|migrations)/]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: migrations/
        args: [--lbt=1, --settings=.isort.cfg]
  - repo: https://github.com/asottile/yesqa
    rev: v1.3.0
    hooks:
      - id: yesqa
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.0
    hooks:
      - id: absolufy-imports
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
