# Generated by Django 4.1.4 on 2022-12-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(help_text="Stock Keeping Unit", max_length=8)),
                ("name", models.CharField(max_length=50)),
                ("price", models.FloatField(max_length=10)),
                ("brand", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "product",
            },
        ),
    ]
